const PlotTypes = {
    ARC: "Arc",
    ELLIPSE: "Ellipse",
    CURVE: "Curve",
    CLOSED_CURVE: "ClosedCurve",
    LUNE: "Lune",
    SECTOR: "Sector",
    GATHERING_PLACE: "GatheringPlace",
    STRAIGHT_ARROW: "StraightArrow",
    ASSAULT_DIRECTION: "AssaultDirection",
    ATTACK_ARROW: "AttackArrow",
    TAILED_ATTACK_ARROW: "TailedAttackArrow",
    SQUAD_COMBAT: "SquadCombat",
    TAILED_SQUAD_COMBAT: "TailedSquadCombat",
    FINE_ARROW: "FineArrow",
    CIRCLE: "Circle",
    DOUBLE_ARROW: "DoubleArrow",
    POLYLINE: "Polyline",
    FREEHAND_LINE: "FreehandLine",
    POLYGON: "Polygon",
    FREEHAND_POLYGON: "FreehandPolygon",
    RECTANGLE: "Rectangle",
    MARKER: "Marker",
    TRIANGLE: "Triangle"
};
export default PlotTypes;
